# Generated by Django 3.2.6 on 2021-10-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passGen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
    ]
